Repository googleapis/java-bigqueryreservation, pull requests merged in 2020-06, with the labels that each got.

#39 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#45 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#47 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#50 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#49 [CHANGE ME] Re-generated to pick up changes from googleapis.
  google-cloud-bigqueryreservation/clirr-ignored-differences.xml
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationServiceClient.java
  google-cloud-bigqueryreservation/src/test/java/com/google/cloud/bigquery/reservation/v1/ReservationServiceClientTest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/Assignment.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/BiReservation.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CapacityCommitment.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateAssignmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteAssignmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/GetBiReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/GetCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/GetReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListAssignmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListAssignmentsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListCapacityCommitmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListCapacityCommitmentsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListReservationsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListReservationsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/MergeCapacityCommitmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/MoveAssignmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/MoveAssignmentRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/Reservation.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationProto.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SearchAssignmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SearchAssignmentsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SplitCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SplitCapacityCommitmentResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/UpdateBiReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/UpdateCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/UpdateReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/proto/google/cloud/bigquery/reservation/v1/reservation.proto
  synth.metadata
Labels: cla: yes, context: full

#58 fix!:Provide C# namespace option for consistent capitalization.
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationServiceClient.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CapacityCommitment.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CapacityCommitmentOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateAssignmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateCapacityCommitmentRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteAssignmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteCapacityCommitmentRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/GetCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/GetCapacityCommitmentRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/GetReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListAssignmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListAssignmentsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListCapacityCommitmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListCapacityCommitmentsRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListCapacityCommitmentsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListReservationsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListReservationsRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListReservationsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/MergeCapacityCommitmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/MergeCapacityCommitmentsRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationProto.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SearchAssignmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SearchAssignmentsRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SearchAssignmentsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SplitCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SplitCapacityCommitmentRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SplitCapacityCommitmentResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/UpdateCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/UpdateReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/proto/google/cloud/bigquery/reservation/v1/reservation.proto
  synth.metadata
Labels: cla: yes, context: full

#65 remove clir ignore
  google-cloud-bigqueryreservation/clirr-ignored-differences.xml
Labels: cla: yes

#63 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#66 ci: switch to secret manager for samples/integration tests
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#72 chore: update github url
  google-cloud-bigqueryreservation/pom.xml
Labels: cla: yes
