Repository googleapis/java-bigqueryreservation, pull requests merged in 2020-05, with the labels that each got.

#12 feat: initial release, update shared-deps
  pom.xml
Labels: cla: yes

#13 chore: update repo names in links
  pom.xml
Labels: cla: yes

#19 Integrate Python GAPIC Microgenerator in googleapis.
  README.md
  synth.metadata
Labels: cla: yes, context: full

#22 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: cla: yes, context: full

#21 docs: Update proto comments for bigqueryreservation v1
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationServiceClient.java
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/package-info.java
  grpc-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationServiceGrpc.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/Assignment.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/AssignmentOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CapacityCommitment.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CapacityCommitmentOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateAssignmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateAssignmentRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/CreateReservationRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteAssignmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteAssignmentRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/DeleteReservationRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/GetCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/GetReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/GetReservationRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListAssignmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListAssignmentsRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListAssignmentsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListCapacityCommitmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListCapacityCommitmentsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListReservationsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListReservationsRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ListReservationsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/MergeCapacityCommitmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/MoveAssignmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/MoveAssignmentRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/Reservation.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationProto.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SearchAssignmentsRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SearchAssignmentsRequestOrBuilder.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SearchAssignmentsResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SplitCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/SplitCapacityCommitmentResponse.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/UpdateCapacityCommitmentRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/java/com/google/cloud/bigquery/reservation/v1/UpdateReservationRequest.java
  proto-google-cloud-bigqueryreservation-v1/src/main/proto/google/cloud/bigquery/reservation/v1/reservation.proto
  synth.metadata
Labels: cla: yes, context: full

#24 docs: update CONTRIBUTING.md to include code formatting (#534)
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, context: full

#29 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#35 deps: bump shared-deps version and add back certain test deps
  pom.xml
Labels: cla: yes
