Repository googleapis/java-bigqueryreservation, pull requests merged in 2020-09, with the labels that each got.

#141 build(ci): enable auto-release in this repo
  .github/workflows/auto-release.yaml
Labels: automerge, cla: yes

#145 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#147 build(ci): add Documentation to not-autorelease script
  .github/workflows/auto-release.yaml
Labels: cla: yes

#149 chore: generate CODEOWNERS from templates
  .repo-metadata.json
Labels: automerge, cla: yes

#151 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#163 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: none

#165 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: bigqueryreservation, cla: yes

#169 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full

#171 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#173 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
