Repository googleapis/java-bigqueryreservation, pull requests merged in 2021-01, with the labels that each got.

#288 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#289 chore: update gapic-generator-java to 0.0.18
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationServiceClient.java
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/stub/GrpcReservationServiceCallableFactory.java
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/stub/ReservationServiceStub.java
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/stub/ReservationServiceStubSettings.java
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#294 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#299 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#302 docs(samples): add quickstart sample
  samples/snippets/src/main/java/com/example/bigqueryreservation/QuickstartSample.java
  samples/snippets/src/test/java/com/example/bigqueryreservation/QuickstartSampleIT.java
Labels: api: bigqueryreservation, cla: yes, samples

#304 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#307 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#308 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: bigqueryreservation, automerge, cla: yes
