Repository googleapis/java-bigqueryreservation, pull requests merged in 2021-05, with the labels that each got.

#383 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: none

#384 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: bigqueryreservation, automerge, cla: yes

#385 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full

#392 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#393 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#395 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#400 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#401 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#404 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full
