Repository googleapis/java-bigqueryreservation, pull requests merged in 2021-07, with the labels that each got.

#430 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#431 chore: remove distributionManagement section
  pom.xml
Labels: api: bigqueryreservation, automerge, cla: yes

#432 chore: remove distributionManagement section
  google-cloud-bigqueryreservation-bom/pom.xml
Labels: api: bigqueryreservation, automerge, cla: yes

#434 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full

#435 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#436 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#439 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#442 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#445 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: bigqueryreservation, automerge, cla: yes

#446 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: bigqueryreservation, automerge, cla: yes
