Repository googleapis/java-bigqueryreservation, pull requests merged in 2021-08, with the labels that each got.

#449 ci: remove java 7 branch protection rule
  .github/sync-repo-settings.yaml
Labels: api: bigqueryreservation, cla: yes

#443 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full

#453 feat!: Java 8 breaking generator changes
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationServiceClient.java
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationServiceSettings.java
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/stub/GrpcReservationServiceStub.java
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/stub/ReservationServiceStubSettings.java
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full

#458 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: bigqueryreservation

#463 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: bigqueryreservation

#464 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: bigqueryreservation, context: full

#474 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: bigqueryreservation

#475 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: bigqueryreservation

#466 chore: update gapic-generator-java version to 2.1.0
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/stub/ReservationServiceStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation, context: full

#480 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  .github/workflows/ci.yaml
Labels: automerge, cla: yes, api: bigqueryreservation

#481 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#482 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#483 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#484 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#485 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#486 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#487 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#488 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#489 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#490 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#491 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#492 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#493 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#494 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#495 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#496 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#497 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#498 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#499 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#500 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#501 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: bigqueryreservation

#503 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: bigqueryreservation
