Repository googleapis/java-bigqueryreservation, pull requests merged in 2021-02, with the labels that each got.

#309 chore: Re-generated to pick up changes from self.
  .kokoro/build.sh
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: none

#310 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: partial

#312 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: partial

#314 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full

#315 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#316 feat: generate sample code in the Java microgenerator
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/ReservationServiceClient.java
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/package-info.java
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full, samples

#318 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full

#321 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#320 chore: update gapic-generator-java to 0.0.20
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/stub/GrpcReservationServiceStub.java
  google-cloud-bigqueryreservation/src/test/java/com/google/cloud/bigquery/reservation/v1/MockReservationServiceImpl.java
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full

#322 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigqueryreservation, cla: yes, context: full

#323 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#324 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#326 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-bigqueryreservation/src/main/java/com/google/cloud/bigquery/reservation/v1/gapic_metadata.json
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#327 ci: test out new sonatype google endpoint
  google-cloud-bigqueryreservation-bom/pom.xml
  pom.xml
Labels: api: bigqueryreservation, automerge, cla: yes

#330 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes

#338 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigqueryreservation, automerge, cla: yes
